-- MTM WIP Application - Stored Procedure Verification Script
-- Generated by Joyride for comprehensive database testing

-- Test database connection and show current database info
SELECT
    'Database Connection Test' as TestType,
    DATABASE
() as CurrentDatabase,
    USER
() as CurrentUser,
    VERSION
() as MySQLVersion,
    NOW
() as TestTime;

-- Count all stored procedures in the database
SELECT
    'Stored Procedure Count' as TestType,
    COUNT(*) as TotalProcedures,
    'All procedures in database' as Description
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'mtm_wip_application_test'
    AND ROUTINE_TYPE = 'PROCEDURE';

-- List all MTM stored procedures by category
SELECT
    'Procedure Inventory' as TestType,
    CASE
        WHEN ROUTINE_NAME LIKE 'inv_%' THEN 'Inventory Operations'
        WHEN ROUTINE_NAME LIKE 'md_%' THEN 'Master Data'
        WHEN ROUTINE_NAME LIKE 'usr_%' THEN 'User Management'
        WHEN ROUTINE_NAME LIKE 'qb_%' THEN 'QuickButtons'
        WHEN ROUTINE_NAME LIKE 'sys_%' THEN 'System Operations'
        ELSE 'Other'
    END as Category,
    ROUTINE_NAME as ProcedureName,
    CREATED as DateCreated,
    LAST_ALTERED as LastModified
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'mtm_wip_application_test'
    AND ROUTINE_TYPE = 'PROCEDURE'
ORDER BY Category, ROUTINE_NAME;

-- Check specific MTM procedures exist (from our analysis)
SELECT 'Critical Procedures Check' as TestType,
    CASE WHEN COUNT(*) >= 45 THEN 'PASS' ELSE 'FAIL' END as Status,
    COUNT(*) as ActualCount,
    '45+' as ExpectedCount,
    'Total MTM procedures' as Description
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'mtm_wip_application_test'
    AND ROUTINE_TYPE = 'PROCEDURE'
    AND (ROUTINE_NAME LIKE 'inv_%' OR
    ROUTINE_NAME LIKE 'md_%' OR
    ROUTINE_NAME LIKE 'usr_%' OR
    ROUTINE_NAME LIKE 'qb_%' OR
    ROUTINE_NAME LIKE 'sys_%');

-- Test QuickButtons procedures specifically (recently fixed)
SELECT 'QuickButton Procedures' as TestType,
    ROUTINE_NAME as ProcedureName,
    CASE WHEN LAST_ALTERED >= '2025-09-20' THEN 'Recently Modified' ELSE 'Older' END as Status,
    LAST_ALTERED as LastModified
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'mtm_wip_application_test'
    AND ROUTINE_TYPE = 'PROCEDURE'
    AND ROUTINE_NAME LIKE 'qb_%'
ORDER BY ROUTINE_NAME;

-- Check procedure parameters for MTM standard pattern
SELECT 'Parameter Validation' as TestType,
    ROUTINE_NAME as ProcedureName,
    PARAMETER_NAME as ParameterName,
    PARAMETER_MODE as Mode,
    DATA_TYPE as DataType
FROM INFORMATION_SCHEMA.PARAMETERS
WHERE SPECIFIC_SCHEMA = 'mtm_wip_application_test'
    AND ROUTINE_TYPE = 'PROCEDURE'
    AND ROUTINE_NAME IN ('qb_quickbuttons_Save', 'qb_quickbuttons_Get_ByUser', 'inv_inventory_Add_Item')
    AND PARAMETER_NAME IN ('p_Status', 'p_ErrorMsg')
ORDER BY ROUTINE_NAME, ORDINAL_POSITION;
